DROP TABLE IF EXISTS markers CASCADE;
CREATE TABLE markers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(60) NOT NULL,
  lat VARCHAR(20) NOT NULL,
  lon VARCHAR(20) NOT NULL,
  category VARCHAR(200),
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
