DROP TABLE IF EXISTS campaigns_users CASCADE;
CREATE TABLE campaigns_users (
  id SERIAL PRIMARY KEY NOT NULL,
  campaign_id INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id VARCHAR(100) REFERENCES users(id) ON DELETE CASCADE,
  is_DM BOOLEAN NOT NULL DEFAULT false
);
